name: hawaii_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


#---------------------------------------------PACKAGES-----------------------------------------------#
dependencies:
  flutter:
    sdk: flutter


  # Utilities Packages:
  http: ^1.2.0
  gap: ^3.0.1
  carousel_slider: ^4.2.1
  liquid_swipe: ^3.1.0
  cached_network_image: ^3.0.0
  image_picker: ^1.0.7
  # Icon Packages:
  cupertino_icons: ^1.0.2
  fluentui_icons: ^1.0.0
  iconsax: ^0.0.8
  lottie: ^3.1.0

  # Fonts:
  line_awesome_flutter: ^2.0.0
  font_awesome_flutter: ^10.4.0
  intl: ^0.19.0
  google_fonts: ^6.1.0

  #State Management
  get: ^4.3.8

  #Others
  flutter_otp_text_field: ^1.1.1
  flutter_native_splash: ^2.2.19
  flutter_svg: ^2.0.10+1

  #Firebase
  firebase_core: ^2.19.4
  firebase_auth: ^4.10.4
  cloud_firestore: ^4.10.4
  firebase_storage: ^11.0.0



#---------------------------------------------PACKAGES END-----------------------------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter





  flutter_lints: ^3.0.1


flutter:


  uses-material-design: true

  #---------------------------------------------Local Assets-----------------------------------------------#
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/videos/
    - assets/icons/logos/
    - assets/icons/category/



